name: Unity License

on:
  workflow_dispatch: {}

jobs:
  activation:
    runs-on: ubuntu-latest
    steps:
      ##############################
      #  Unity-request-activation  #
      ##############################
      - id: getManualLicenseFile
        uses: game-ci/unity-request-activation-file@v2.0-alpha-1

      ####################
      #  Upload artifact #
      ####################
      - uses: actions/upload-artifact@v3
        with:
          name: UnityLicenseFile
          path: ${{ steps.getManualLicenseFile.outputs.filePath }}
